#!/bin/sh

if [[ "$1" == "up" ]]; then
    pactl set-sink-volume 0 +1% && eww -c ~/.config/eww/bar update volume_percent=$(amixer -D pulse sget Master | grep 'Left:' | awk -F'[][]' '{ print $2 }' | tr -d '%')
elif [[ "$1" == "down" ]]; then
    pactl set-sink-volume 0 -1% && eww -c ~/.config/eww/bar update volume_percent=$(amixer -D pulse sget Master | grep 'Left:' | awk -F'[][]' '{ print $2 }' | tr -d '%')
fi
