config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
    chmod: '644'
  d_oh-my-zsh:
    src: oh-my-zsh
    dst: ~/.oh-my-zsh
    chmod: '755'
  d_latte:
    src: config/latte
    dst: ~/.config/latte
    chmod: '755'
  d_wallpapers:
    src: local/share/wallpapers
    dst: ~/.local/share/wallpapers
  d_konsole:
    src: local/share/konsole
    dst: ~/.local/share/konsole
  d_color-schemes:
    src: local/share/color-schemes
    dst: ~/.local/share/color-schemes
  d_icons:
    src: icons
    dst: ~/.icons
profiles:
  something:
    dotfiles:
    - f_zshrc
    - d_oh-my-zsh
    - d_latte
    - d_wallpapers
    - d_konsole
    - d_color-schemes
    - d_icons
